/**
 * Core entity types for SettleUp.
 *
 * Mirrors the data model in "SettleUp - Scope, Data Model & Roadmap" §9 and the
 * Phase-1 subset in "Phase 1 Plan" §3.3. All money is integer cents (never floats).
 * All ids are client-generated UUIDs so records created offline keep their identity.
 */

/** Integer number of ZAR cents. Never use floating point for money. */
export type Cents = number;

export type SplitMethod = "equal" | "exact" | "percent" | "shares" | "salary";

export type Category =
  | "groceries"
  | "rent"
  | "utilities"
  | "eatingout"
  | "transport"
  | "household"
  | "entertainment"
  | "other";

export type MemberRole = "owner" | "member";
export type MemberStatus = "active" | "invited" | "left";

/** Sync metadata carried by every synced record (scope doc §9.4). */
export interface SyncMeta {
  createdAt: string; // ISO timestamp
  updatedAt: string;
  /** Monotonic logical clock for last-writer-wins conflict resolution (Phase 2). */
  version: number;
  /** Actor user id; tiebreaker when two edits share a clock value. */
  updatedBy: string | null;
  /** Soft-delete tombstone. Null = live. */
  deletedAt: string | null;
}

export interface User {
  id: string; // from Supabase Auth
  email: string;
  displayName: string;
  avatarUrl: string | null;
}

export interface Profile {
  userId: string;
  /** Private; powers salary-proportional splits. Null = not provided. */
  monthlySalaryCents: Cents | null;
  defaultSplitMethod: SplitMethod | null;
  defaultGroupId: string | null;
  /** Whether group members may see the salary figure (default false). */
  salaryVisible: boolean;
}

export interface Group extends SyncMeta {
  id: string;
  name: string;
  currency: "ZAR";
  simplifyDebts: boolean;
  archived: boolean;
  createdBy: string;
}

export interface GroupMember extends SyncMeta {
  id: string;
  groupId: string;
  /** Null for a placeholder (non-app) member. */
  userId: string | null;
  /** Used when userId is null. */
  placeholderName: string | null;
  role: MemberRole;
  status: MemberStatus;
}

export interface ExpensePayer {
  memberId: string; // group_member id — who paid
  paidCents: Cents;
}

export interface ExpenseSplit {
  memberId: string; // group_member id — who is charged
  shareCents: Cents;
  /** Raw input for shares/percent/salary methods, kept for audit. */
  weight?: number;
}

export interface Expense extends SyncMeta {
  id: string;
  groupId: string;
  description: string;
  category: Category;
  /** Total; must equal the sum of payers' paidCents and of splits' shareCents. */
  amountCents: Cents;
  /** The expense date (defaults to now); ISO timestamp. */
  spentAt: string;
  splitMethod: SplitMethod;
  payers: ExpensePayer[];
  splits: ExpenseSplit[];
  receiptUrl: string | null;
  /** Set if generated by a recurring rule. */
  recurringId: string | null;
  note: string | null;
  createdBy: string;
  /** Client-only: awaiting sync to the backend (drives the amber sync pill). */
  pending?: boolean;
}

export interface Settlement extends SyncMeta {
  id: string;
  groupId: string;
  fromMemberId: string; // payer
  toMemberId: string; // payee
  amountCents: Cents;
  settledAt: string;
}

export interface RecurringExpense extends SyncMeta {
  id: string;
  groupId: string;
  description: string;
  category: Category;
  /** Null if the amount is entered each occurrence (variable bills). */
  amountCents: Cents | null;
  frequency: "weekly" | "monthly";
  /** Day-of-week (weekly) or day-of-month (monthly, clamped 1–28). */
  anchor: number;
  nextRun: string; // ISO date
  endDate: string | null;
  payerMemberId: string;
  splitMethod: SplitMethod;
  participantMemberIds: string[];
  paused: boolean;
}

export interface ShoppingItem extends SyncMeta {
  id: string;
  groupId: string;
  name: string;
  qty: number | null;
  estPriceCents: Cents | null;
  checked: boolean;
  addedBy: string;
}

export type ActivityType =
  | "expense_added"
  | "expense_edited"
  | "expense_deleted"
  | "settled"
  | "member_joined"
  | "recurring_generated";

export interface Activity {
  id: string;
  groupId: string;
  actorId: string;
  type: ActivityType;
  /** The affected record's id. */
  targetId: string;
  createdAt: string;
}
